@startuml
start

:Запустить приложение;

:Загрузить данные\nиз базы данных;

:Отобразить список\nпоследовательностей;

:Пользователь выбирает\nпоследовательность и\nнажимает кнопку "Play";

:Инициализировать\nпервую фазу;

:Запустить foreground-сервис;

:Отобразить уведомление;

repeat
  :Запустить обратный отсчёт;
  
  while (Время фазы > 0?) is (Да)
    :Обновить оставшееся время;
    :Обновить уведомление;
    :Обновить UI;
    :Подождать 1 секунду;
  endwhile (Нет)
  
  :Воспроизвести\nзвуковой сигнал;
  
  if (Есть повторения\nтекущей фазы?) then (Да)
    :Увеличить счётчик повторений;
    :Сбросить время фазы;
  else (Нет)
    if (Есть следующая фаза?) then (Да)
      :Перейти к следующей фазе;
      :Сбросить счётчик повторений;
      :Установить время новой фазы;
    else (Нет)
      :Завершить последовательность;
      :Воспроизвести\nсигнал завершения;
      break
    endif
  endif
  
repeat while (Последовательность\nне завершена?) is (Да)

:Показать состояние завершения;

:Остановить foreground-сервис;

:Удалить уведомление;

stop

@enduml
